### ISSUE TITLE
vmware-horizon-client-bin installation issue

### ISSUE THREAD

**Issue by fluffynuts** [AstroFloyd/Gentoo-overlay#1]
Good day

I've only been using Gentoo for a few months now (moved away from Debian / derivatives after about 16 years in that land), so bear with me if I have some terminology wrong.

I found this overlay to contain app-emulation/vmware-horizon-client-bin, thanks to the Zugaina search engine. I have added with
`layman -f -a AstroFloyd`
and masked all from this overlay:
`*/*::AstroFloyd`
and then unmasked vmware-horizon-client-bin in package.unmask:
`app-emulate/vmware-horizon-client-bin`
and added to package.accept_keywords:
`app-emulation/vmware-horizon-client-bin ~amd64`

Now, when I attempt to:
`emerge vmware-horizon-client-bin -a`
I get the message: 
`!!! A file listed in the Manifest could not be found: /var/lib/layman/AstroFloyd/app-emulation/vmware-horizon-client-bin/vmware-horizon-client-bin-4.3.0.ebuild`
And, sure enough, said file is not there. However, 
`emerge --search vmware-horizon-client-bin`
yeilds:
`
*  app-emulation/vmware-horizon-client-bin
      Latest version available: 4.2.0
      Latest version installed: [ Not Installed ]
      Size of files: 55,427 KiB
      Homepage:      https://my.vmware.com/web/vmware/info/slug/desktop_end_user_computing/vmware_horizon_clients/4_0
      Description:   Binary version of VMware horizon client
      License:       vmware
`
So it looks like I should be getting 4.2.0 and the Manifest is pointing at 4.3.0. Trying to hack around the issue (as if 4.3.0 had been incorrectly input into the Manifest), I get SHA mismatch errors, so it definitely looks like there's supposed to be a 4.3.0 -- but I'm not getting it, even after
`emerge --sync`
and I have post-sync hooks to update overlays, so it really should. Also, doing
`eix-update`
gives me errors on AstroFloyd:
`[9] "AstroFloyd" /var/lib/layman/AstroFloyd (cache: parse|ebuild*#metadata-md5#metadata-flat#assign)
     Reading category  26|164 ( 15): app-text... * ERROR: app-text/epubcheck-1.0.5::AstroFloyd failed (depend phase):
 *   use() calls are not allowed in global scope
 * 
 * Call stack:
 *                ebuild.sh, line 611:  Called source '/var/lib/layman/AstroFloyd/app-text/epubcheck/epubcheck-1.0.5.ebuild'
 *   epubcheck-1.0.5.ebuild, line  20:  Called use 'amd64'
 *                ebuild.sh, line  78:  Called die
 * The specific snippet of code:
 *              eval "${x}() { die \"\${FUNCNAME}() calls are not allowed in global scope\"; }"
 * 
 * If you need support, post the output of `emerge --info '=app-text/epubcheck-1.0.5::AstroFloyd'`,
 * the complete build log and the output of `emerge -pqv '=app-text/epubcheck-1.0.5::AstroFloyd'`.
 * Working directory: '/usr/lib64/python2.7/site-packages'
 * S: '/epubcheck-1.0.5'
`
I know that references other packages, but I thought you might be interested. The results from the recommended emerge commands also contain error messages about use() in the global scope. I can paste the full output if you like -- but there's rather a lot :/

**Comment by AstroFloyd** [comment]
Apologies, I missed your message.

I bumped the version and regenerated the Manifest.

The trouble with this ebuild is that the program doesn't work yet.  When I install the program by hand, it runs properly, if I install it using this ebuild, it doesn't.  Something is missing, but I ran out of time to work on this.  I hope you have any luck with this, but I recommend installing by hand if it doesn't work.  If you find what is missing, please let me know.

Edit: From my notes: I had to create a symlink in /usr/lib  ("ln -s libudev.so  libudev.so.0) for the manually installed version to work.

**Comment by fluffynuts** [comment]
Closing as this (thankfully) no longer applies to me. I don't need the client any more.
